name: Sanity Checks

on: [push]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install flake8 black isort
        working-directory: ${{ github.workspace }}

      - name: Check PEP8 compliance with Flake8
        run: |
          flake8 --config .github/linters/.flake8 --exclude=alembic .
        working-directory: ${{ github.workspace }}

      - name: Format code with Black
        run: |
          black --config .github/linters/.python-black .
        working-directory: ${{ github.workspace }}
